Jd appointment api updates - Abhishek

diff --git a/bin/manage_ts_service b/bin/manage_ts_service
--- a/bin/manage_ts_service
+++ b/bin/manage_ts_service
@@ -19,7 +19,7 @@ cd $SCRIPT_BIN_DIR/../service-data/logs
 LOG_BASE=`pwd`
 ERROR_LOG_FILE=$LOG_BASE/error_log.txt
 
-JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64
+JAVA_HOME=/home/ec2-user/java-1.8.0-openjdk-1.8.0
 VM_ARGUMENTS=" "
 PROGRAM_ARGUMENTS="com.techstomach.ehs.service.MainService server $CONFIG_BASE/main.yml"
 
@@ -52,7 +52,7 @@ start() {
     message "VM_ARGUMENTS=$VM_ARGUMENTS"
     message "PROGRAM_ARGUMENTS=$PROGRAM_ARGUMENTS"
 
-    SERVICE_PID=`ps -ef |grep   java | grep -v grep | grep AppStarterVerticle | awk '{print $2;}'`
+    SERVICE_PID=`ps -ef |grep   java | grep -v grep | grep MainService | awk '{print $2;}'`
     if [ -n "$SERVICE_PID" ]; then
       echo "ERROR: the service is already running with pid = $SERVICE_PID"
       exit 1
@@ -67,7 +67,25 @@ start() {
       echo "ERROR: service is not running"
     fi
 }
+teststart() {
+    message "SCRIPT_BIN_DIR=$SCRIPT_BIN_DIR"
+    message "HOSTNAME=$HOSTNAME"
+    message "CONFIG_BASE=$CONFIG_BASE"
+    message "PID_BASE=$PID_BASE"
+    message "ERROR_LOG_FILE=$ERROR_LOG_FILE"
+    message "CLASSPATH=$CLASSPATH"
+    message "JAVA_HOME=$JAVA_HOME"
+    message "VM_ARGUMENTS=$VM_ARGUMENTS"
+    message "PROGRAM_ARGUMENTS=$PROGRAM_ARGUMENTS"
 
+    SERVICE_PID=`ps -ef |grep   java | grep -v grep | grep MainService | awk '{print $2;}'`
+    if [ -n "$SERVICE_PID" ]; then
+      echo "ERROR: the service is already running with pid = $SERVICE_PID"
+      exit 1
+    fi
+
+    $JAVA_HOME/bin/java $VM_ARGUMENTS -cp $CLASSPATH $PROGRAM_ARGUMENTS
+}
 stop() {
     message "SCRIPT_BIN_DIR=$SCRIPT_BIN_DIR"
     message "HOSTNAME=$HOSTNAME"
@@ -113,6 +131,10 @@ case "$1" in
     start)
         message "start method called"
         start
+        ;;
+    teststart)
+        message "teststart method called"
+        teststart
         ;;
     stop)
         message "stop method called"
